name: substra_single_node
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11 # Substrafl and Substra are compatible with Python versions 3.9, 3.10 and 3.11 on Windows, MacOS and Linux and currently Python latest is 3.12.4
  - pip
  - pip:
    - substrafl # Substra is a dependency of SubstraFL, so it will be automatically installed. https://docs.substra.org/en/stable/examples/substrafl/get_started/run_mnist_torch.html
    - matplotlib==3.6.3 # Based on requirements.txt from the tutorial
    - scikit-learn==1.3.1 # Based on requirements.txt from the tutorial
    - pandas==1.5.3 # Based on requirements.txt from the tutorial
    - substra # Based on requirements.txt from the tutorial
    - substratools # Based on requirements.txt from the tutorial

# conda env create -f substra-environment.yml